select ANIMAL_ID, NAME, if(SEX_UPON_INTAKE like 'Intact%', 'X', 'O') as 중성화
from ANIMAL_INS
order by ANIMAL_ID

SELECT ANIMAL_ID, NAME, 
    CASE WHEN SEX_UPON_INTAKE LIKE 'Intact%' THEN 'X' 
    ELSE 'O' END as 중성화
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;